name: The Legal Coda
description: "Processes and Thoughts on Coding the Law & Treating the Law as Code"
url: http://coda.caseykuhlman.com
safe: true
lsi: false
pygments: true
pagination: 10
permalink: /entries/:year/:title.html