# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:        underWater desert Blogging
url:         http://blog.caseykuhlman.com
# url:         /
author:      
  name:    Casey Kuhlman
  email:   caseykuhlman@watershedlegal.com
  github:  compleatang
  tumblr:  compleatang
  twitter: compleatang
  lastfm:  compleatang
exclude: [".gitignore", ".ruby-version", ".ruby-gemset", "README.md", "Rakefile", "_drats"]

subscribe_rss:  ./rss.xml
subscribe_atom: ./atom.xml
atom_path:      ./atom.xml
rss_path:       ./rss.xml

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# root:            "home/coda/sites/csk/udb/_site/"
root:            /
destination:     "_site/htdocs"
permalink:       "entries/:year/:title.html"
safe:            true
lsi:             false
pygments:        true
paginate:        10
markdown:        redcarpet
categories_path: "categories.html"
excerpt_link:    "Read more &rarr;"
titlecase:       true

# ----------------------- #
#      Personalized       #
# ----------------------- #

images_dir:  "assets/images"
scripts_dir: "assets/scripts"
styles_dir:  "assets/styles"


# ----------------------- #
#        Comments         #
# ----------------------- #

comments :
  provider : disqus
  disqus :
    short_name : caseykuhlman

# ----------------------- #
#       Analytics         #
# ----------------------- #

analytics :
  provider : getclicky
  getclicky : 
    site_id : 66416567

# ----------------------- #
#         Feeds           #
# ----------------------- #

feeds:
  provider: feedburner
  feedburner:
    rss_feed: "caseykuhlman"