# ----------------------- #
#      Main Configs       #
# ----------------------- #

name:        underWater desert Blogging
url:         https://blog.caseykuhlman.com
url_plain:   http://blog.caseykuhlman.com
description: Processes and Thoughts on Lots of Matters

author:
  name:       Casey Kuhlman
  email:      caseykuhlman@watershedlegal.com
  github:     compleatang
  tumblr:     compleatang
  twitter:    compleatang
  lastfm:     compleatang
  googleplus: CaseyKuhlman1976

exclude: [".gitignore", ".ruby-version", ".ruby-gemset", "README.md", "Rakefile", "_drafts"]

subscribe_rss:  http://blog.caseykuhlman.com/rss.xml
rss_path:       http://blog.caseykuhlman.com/rss.xml

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

root:            /
destination:     "_site/htdocs"
permalink:       "entries/:year/:title.html"
safe:            true
lsi:             false
pygments:        true
paginate:        10
markdown:        redcarpet
categories_path: "categories.html"
excerpt_link:    "Read more &rarr;"
titlecase:       true

# ----------------------- #
#      Personalized       #
# ----------------------- #

images_dir:  "/assets/images"
scripts_dir: "/assets/scripts"
styles_dir:  "/assets/styles"


# ----------------------- #
#        Comments         #
# ----------------------- #

comments :
  provider : disqus
  disqus :
    short_name : caseykuhlman

# ----------------------- #
#       Analytics         #
# ----------------------- #

analytics :
  provider : getclicky
  getclicky :
    site_id : 66416567

# ----------------------- #
#         Feeds           #
# ----------------------- #

feeds:
  provider: feedburner
  feedburner:
    rss_feed: "caseykuhlman"
