disablePathToLower = true
enableGitInfo = true
baseurl = "/"

title = "underWater desert Blogging"
theme = "hello-friend-ng"
copyright = "<a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">All Content Licensed CC BY-NC-SA 4.0</a>"
languageCode = "en-us"

[author]
  name = "Casey Kuhlman"

[params]
  dateform        = "2 Jan, 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "A Site About Resilience and Authoritarianism"  
  subtitle = "A Site About Resilience and Authoritarianism"
  homeSubtitle = "A Site About Resilience and Authoritarianism"
  keywords = "legaltech, resilience, authoritarianism"

  contentTypeName = "posts"
  defaultTheme = "dark"
  disableReadOtherPosts = false
  readOtherPosts = "More good content ->"

  gitUrl = "https://github.com/compleatang/site/commit/"

  customJS = [
    "/js/udb.js",
    "//static.getclicky.com/js"
  ]

  [params.logo]
    logoText = "cd ~/"
    logoHomeLink = "/"

  [[params.social]]
    name = "keybase"
    url = "https://keybase.com/compleatang"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/compleatang"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/compleatang/"

  [[params.social]]
    name = "github"
    url = "https://github.com/compleatang/"

  [[menu.main]]
    identifier = "posts"
    name       = "Entries"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "Me, About"
    url        = "/about"

  [[menu.main]]
    identifier = "muniments"
    name       = "Muniments"
    url        = "/muniments"

[taxonomies]
  tag      = "tags"
  category = "categories"